### ISSUE TITLE
get restrictedCIDRs from the cluster API

### ISSUE THREAD

**Issue by squeed** [openshift/cluster-kube-apiserver-operator#106]
The installer now creates a `Cluster.cluster.k8s.io/v1alpha1` object, which is the correct way for operators to determine information about IP space.

Instead of parsing the old tectonic installer configuration, the operator should determine its list of restricted CIDRs from this object instead.

**Comment by squeed** [comment]
You can find the actual type at https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/apis/cluster/v1alpha1/cluster_types.go

**Comment by sttts** [comment]
@damemi that `Cluster.cluster.k8s.io/v1alpha1` is not in the installer, so it solves the import cycle.
