### ISSUE TITLE
openshift-kube-apiserver logs are full of TLS handshake errors

### ISSUE THREAD

**Issue by smarterclayton** [openshift/cluster-kube-apiserver-operator#127]
It looks like its coming from the pod network, but hard to say for sure.

```
I1116 23:07:53.364992       1 logs.go:49] http: TLS handshake error from 10.0.11.206:22630: EOF
I1116 23:07:53.468272       1 logs.go:49] http: TLS handshake error from 10.0.22.71:5446: EOF
I1116 23:07:53.485773       1 logs.go:49] http: TLS handshake error from 10.0.81.142:42664: EOF
I1116 23:07:53.571327       1 logs.go:49] http: TLS handshake error from 10.0.56.194:57970: EOF
I1116 23:07:53.601100       1 logs.go:49] http: TLS handshake error from 10.0.11.206:7721: EOF
I1116 23:07:53.947873       1 logs.go:49] http: TLS handshake error from 10.0.67.121:4099: EOF
I1116 23:07:54.203697       1 logs.go:49] http: TLS handshake error from 10.0.74.56:45909: EOF
I1116 23:07:54.309702       1 logs.go:49] http: TLS handshake error from 10.0.88.7:11357: EOF
```

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/21497/pull-ci-openshift-origin-master-e2e-aws/857/artifacts/e2e-aws/pods/openshift-kube-apiserver_openshift-kube-apiserver-ip-10-0-47-95.ec2.internal_apiserver.log.gz

Possibly a misconfigured infrastructure component

**Comment by smarterclayton** [comment]
I did some research and this looks like port scanners on AWS.  On a single cluster for the 30 minutes while tests were running, all 3 apiservers recorded:

```
N     IP
5607 10.0.22.113
5614 10.0.26.222
5650 10.0.38.21
5656 10.0.44.215
5662 10.0.5.216
5654 10.0.53.53
5653 10.0.61.92
5678 10.0.64.163
5670 10.0.76.67
5667 10.0.8.19
5685 10.0.92.68
5696 10.0.93.53
```

None of those were in use by our cluster.

**Comment by smarterclayton** [comment]
Nothing to do here I guess

**Comment by sttts** [comment]
Those are ELB pings I believe. Can we change them to use https /healthz requests?

**Comment by DanyC97** [comment]
the installer need to change - see https://github.com/openshift/installer/issues/923
