### ISSUE TITLE
Allow runtime/default seccomp profile in the built-in SCCs

### ISSUE THREAD

**Issue by pjbgf** [openshift/cluster-kube-apiserver-operator#1325]
Currently, all default SCCs (except `privileged`) block users from setting seccomp to `runtime/default`. The current behaviour seems to be a disservice as it blocks workloads to use more restrictive security controls, which may lead to folks simply set a workload SCC to `privileged` in order to "get it to work".
This is becoming a larger problem as folks around the OSS community and the private sector start shipping workloads with seccomp set to `runtime/default` - which is the recommended setting by CIS Benchmark for a few years now. They are now facing a few options:
- Do nothing and effectively not support OpenShift clusters by default.
- Create documentation or deployment manifests that are OpenShift-specific, which aims to remove the seccomp setting. (e.g. https://github.com/open-policy-agent/gatekeeper/pull/842 https://github.com/open-policy-agent/gatekeeper/issues/790 https://github.com/weaveworks/flux2-openshift/issues/10#issuecomment-1044617904)
- Create custom SCC to bypass such restriction.
- Set SCC to `privileged`.

The **suggested change is to allow all default SCCs to support**:
  - `unconfined` (current Kubernetes default for backwards compatibility)
  - `runtime/default`  (future Kubernetes default and safer position)

I am not entirety sure of the longevity and future plans of SCC. However, making this change will:
- Help developers to seamless support OpenShift (from a seccomp perspective).
- Help companies to be CIS Benchmark compliant.
- Support the new defaults from Kubernetes upstream.

Looking forward to hear some thoughts around and understand how receptive the maintainers would be to the above.

cc: @JAORMX @jhrozek @saschagrunert 

--- 
Upstream Context:
- Around 2016 Docker created a default seccomp profile and enabled by default. The same profile was introduced into Kubernetes as `docker/default` and was later renamed to `runtime/default`.
- Kubernetes `1.19`: Seccomp made GA having profile `unconfined` by default.
- Kubernetes `1.22`: SeccompDefault feature gate created, enabling users to switch from `unconfined` to `runtime/default` across the entire cluster. 
- Kubernetes `1.25` (planned): SeccompDefault feature gate is enabled by default, meaning that all workloads will have seccomp profile `runtime/default` unless otherwise set on a per workload (pod or container) basis.

**Comment by cbandy** [comment]
[BZ - 2010564](https://bugzilla.redhat.com/show_bug.cgi?id=2010564) seems to talk about the same issue.

**Comment by nyoxi** [comment]
@pjbgf Could you please elaborate on how/where was this issue fixed? Thanks.

**Comment by pjbgf** [comment]
@nyoxi I don't think the issue was resolved, I closed it due to lack of activity within the year it was opened.
