### ISSUE TITLE
Only one openshift-apiserver pod out of three is responding

### ISSUE THREAD

**Issue by vrutkovs** [openshift/cluster-kube-apiserver-operator#158]
On GCP 4.0 on CentOS apiserver runs on 3 masters, but only one pod is responding. This breaks openshift-kube-apiserver, which uses `api` server to communicate - most of the requests are failing.
```
$ oc get pods -n openshift-apiserver -o wide
NAME              READY     STATUS    RESTARTS   AGE       IP            NODE
apiserver-dz57l   1/1       Running   0          21m       10.131.0.44   vrutkovs-ig-m-4m83
apiserver-nrc9c   1/1       Running   1          3m        10.129.0.23   vrutkovs-ig-m-23z7
apiserver-zsl6n   1/1       Running   1          3m        10.130.0.23   vrutkovs-ig-m-42bb
# curl -kLvs https://10.129.0.23:8443/apis/apps.openshift.io/v1
<hangs>
# curl -kLvs https://10.130.0.23:8443/apis/apps.openshift.io/v1
<hangs>
# curl -kLvs https://10.131.0.44:8443/apis/apps.openshift.io/v1
<works immediately>
```
This works fine if I adjust `ds/apiserver` to match only one known-to-work master node. All masters are created from the same instance group and get the same firewall rules applied.

This doesn't seem to affect AWS, but should happen on libvirt with 3 masters

**Comment by sttts** [comment]
Can you check from inside the pods whether the API servers answer? kubectl exec ....

In other words: is it a network problem?

**Comment by vrutkovs** [comment]
Yep, `oc -n openshift-apiserver exec <pod name> -- curl -kLvs https://localhost:8443` works fine

**Comment by squeed** [comment]
It's an MTU problem; the nodes have an mtu of 1460. We need to fix this, either in the network operator (someday) or the installer (easier)

**Comment by sdodson** [comment]
> It's an MTU problem; the nodes have an mtu of 1460. We need to fix this, either in the network operator (someday) or the installer (easier)

How would you propose the installer fix this without changes to the operator?

**Comment by vrutkovs** [comment]
It was a wrong MTU on GCE which was breaking us

**Comment by squeed** [comment]
A couple ways to do this, but for GCP, the SDN mtu will always be 1410. We already have https://jira.coreos.com/browse/SDN-250 to figure out the MTU story in a sustainable way.
