### ISSUE TITLE
kube-apiserver restarting on bootstrap node

### ISSUE THREAD

**Issue by abhinavdahiya** [openshift/cluster-kube-apiserver-operator#175]
kube-apiserver seems to be restarting on the bootstrap node causing the installer to fail.

one example is https://github.com/openshift/installer/issues/964
another https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/251/pull-ci-openshift-machine-config-operator-master-e2e-aws/770/

This causes the master nodes to never come up.

/cc @deads2k 
^^ not sure who else to cc :innocent:

**Comment by mfojtik** [comment]
@abhinavdahiya or just tag @openshift/sig-master :-)
