### ISSUE TITLE
regenerate-certificates has too many CA's in csr-signer

### ISSUE THREAD

**Issue by rphillips** [openshift/cluster-kube-apiserver-operator#470]
Running `cluster-kube-apiserver-operator regenerate-certificates` on a failed master causes the `/etc/kubernetes/static-pod-resources/kube-controller-manager-pod-5/secrets/csr-signer/tls.crt` file to contain two certificates. The controller-manager CSR signer then fails signing certificates with this error:

```
E0509 20:04:43.804526       1 controllermanager.go:541] Error starting "csrsigning"
F0509 20:04:43.804566       1 controllermanager.go:240] error starting controllers: failed to start certificate controller: error parsing CA cert file "/etc/kubernetes/static-pod-resources/secrets/cs
r-signer/tls.crt": {"code":1003,"message":"the PEM file should contain only one object"}
```

Manually removing the offending certificates from tls.crt and rebooting the node fixes the issue allowing the controller-manager to sign certificates.

/cc @tnozicka

**Comment by wking** [comment]
Can we close this with #471 landed?

**Comment by rphillips** [comment]
I was verifying it and ran into an issue which may be fixed here: https://github.com/openshift/cluster-kube-apiserver-operator/pull/472. I'll close this once verified.

**Comment by rphillips** [comment]
Works!
