### ISSUE TITLE
The Pod and Service cidr shold not be hardcoded.

### ISSUE THREAD

**Issue by abhinavdahiya** [openshift/cluster-kube-apiserver-operator#50]
https://github.com/openshift/cluster-kube-apiserver-operator/blob/e6ff4c7236894c6c10cb35e31cfe568a10939741/bindata/v3.11.0/kube-apiserver/defaultconfig.yaml#L16-L17

These are configurable.

**Comment by sttts** [comment]
For phase 1+2 this could/should be part of an override file `--config-file-override network-overrrides.yaml` to the render command.

**Comment by deads2k** [comment]
@sanchezl got a cluster running, built the operator, and delivered a change to it.

/assign @sanchezl 

your reward for a job well done :)

**Comment by deads2k** [comment]
Hint: here is where you observe it: https://github.com/openshift/cluster-kube-apiserver-operator/blob/master/pkg/operator/observe_config.go  and here is the source of the information: `oc -n kube-system get cm cluster-config-v1 -oyaml`
