### ISSUE TITLE
How to update kube apiserver to point to a new file

### ISSUE THREAD

**Issue by gyliu513** [openshift/cluster-kube-apiserver-operator#561]
I was trying to update the kubeapiserver CR resources to enable KMS plugin at https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/#encrypting-your-data-with-the-kms-provider by using command `oc edit kubeapiservers.operator.openshift.io`, but the problem is the new parameter `--encryption-provider-config` need to point to a file, so how can I make the parameter point to a new file? I was using OCP 4.1. Thanks.

**Comment by deads2k** [comment]
Right now there is no way to have an additional file laid down with kube-apiserver pods.  We don't have any near term plans to make such a thing configurable.  If your mission is to configure KMS, that sounds like a reasonable RFE that @knewcomerRH may be able to help you write up.

**Comment by gyliu513** [comment]
@knewcomerRH any comments for this?
