### ISSUE TITLE
How to change event-ttl of API Server

### ISSUE THREAD

**Issue by Daiki-Kawanuma** [openshift/cluster-kube-apiserver-operator#805]
Hi, 
I want to edit event-ttl of API Server.

I found official documents of OCP 3.11
https://docs.openshift.com/container-platform/3.11/install_config/master_node_configuration.html
```
apiServerArguments:
  event-ttl:
  - "15m"
```

In OCP 4.3, same as OCP 3.11, I think that I can change event-ttl by editing CRD of "kubeapiservers.operator.openshift.io".
```
# oc get kubeapiservers.operator.openshift.io/cluster -o yaml
apiVersion: operator.openshift.io/v1
kind: KubeAPIServer
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  creationTimestamp: "2020-03-18T23:46:56Z"
  generation: 3
  name: cluster
  resourceVersion: "428767"
  selfLink: /apis/operator.openshift.io/v1/kubeapiservers/cluster
  uid: 927aefc8-04e6-437b-9965-5404dd5da7e8
spec:
  logLevel: ""
  managementState: Managed
  observedConfig:    
    apiServerArguments:
      feature-gates:
      - RotateKubeletServerCertificate=true
      - SupportPodPidsLimit=true
      - NodeDisruptionExclusion=true
      - ServiceNodeExclusion=true
      - SCTPSupport=true
      - LegacyNodeRoleBehavior=false
```

Is my understanding right?

**Comment by sttts** [comment]
ObservedConfig is maintained by the operator. No way to change that by the user. UnsupportedConfigOverrides would do, but as the name states: without support. It will block upgrades.

**Comment by Daiki-Kawanuma** [comment]
Hi, @sttts 
I'm very thankful for your prompt reply.

I understood editing `event-ttl` is unsupported and Operator blocks upgrades.
My question has been resolved.

regards,
Daiki
