### ISSUE TITLE
Use ServiceAccountToken volumes

### ISSUE THREAD

**Issue by JoaoBraveCoding** [openshift/cluster-kube-apiserver-operator#834]
I have a deployment of Openshift 4.3 and I wanted to use [Service Account Token Volume Projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) however to do this I have to pass these flags to the API server:
```
--service-account-issuer
--service-account-signing-key-file
--service-account-api-audiences
```

How can this be accomplished? Is it by editing the resource `kubeapiservers.operator.openshift.io/cluster` if so how because looking at the resource and reading what doc was available I was not able to figure it out?

**Comment by sttts** [comment]
This will be part of 4.4, soon to be released. There is no supported way in 4.3.
