### ISSUE TITLE
Consume service-account.key instead of service-account.pub

### ISSUE THREAD

**Issue by wking** [openshift/cluster-kube-apiserver-operator#96]
Since openshift/installer@57127ec (coreos/tectonic-installer#3270), the installer sets a `kube-apiserver` secret in the `kube-system` with [both `service-account.key` and `service-account.pub`][1].  We also do that [for the `openshift-apiserver` secret][2].  But the public key can be computed from the private key, so it would be nice to not have to set both in the same secret.  It looks like [the kube-controller-manager operator uses the private key][3] (although I haven't found code where it pulls it from the installer-generated secret); can we update this operator to use the private key too?  Or should the installer be setting separate secrets for each operator?  Or something (again, the connections are not very clear to me ;)?

[1]: https://github.com/openshift/installer/blob/master/pkg/asset/manifests/content/bootkube/kube-apiserver-secret.go#L23-L24
[2]: https://github.com/openshift/installer/blob/master/pkg/asset/manifests/content/bootkube/openshift-apiserver-secret.go#L25-L26
[3]: https://github.com/openshift/cluster-kube-controller-manager-operator/blob/9f1c8219d40daae907d8f3d7cd8064ce608c9222/bindata/bootkube/manifests/secret-service-account-private-key.yaml#L7

**Comment by sttts** [comment]
Why should we make a private key visible to a component if that is not strictly necessary. Especially the apiserver is exposed to the outer network and hence especially sensitive.

**Comment by wking** [comment]
> Why should we make a private key visible...

Sounds like you want the "use two secrets" approach.  What does each operator need, and what should the secrets be called?

**Comment by sttts** [comment]
The secrets are operator-specific already now (in the openshift-kube-* namespaces), rendered by the operator during bootstrapping.

Wondering about the kube-apiserver secret. That should be deleted I guess. Is there any consumer left?
